language: node_js
node_js:
   - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

before_script:
   - yarn global add firebase-tools
   - yarn global add @angular/cli

script:
   - ng build --prod --aot
